package com.eidiko.bank.credit;

import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;

public class SaveInLog {

    public SaveInLog(String cust_id, String mobile_number, String person_name, String credit_card_family, String cardnum, String cvv, String expiry) throws IOException {
        BufferedWriter out = null;

        try {
            FileWriter fstream = new FileWriter("log.txt", true); //true tells to append data.
            out = new BufferedWriter(fstream);
            System.out.println("customerID: "+cust_id+" mobile number: "+mobile_number+" person name: "+person_name+" credit card family: "+
                    credit_card_family+"... Generated by the code:--  Card Number: "+cardnum+" CVV of card: "+cvv+" Expiry date:"+expiry );
            out.write("customerID: "+cust_id+" mobile number: "+mobile_number+" person name: "+person_name+" credit card family: "+
                    credit_card_family+"... Generated by the code:--  Card Number: "+cardnum+" CVV of card: "+cvv+" Expiry date:"+expiry );
            out.newLine();
        }

        catch (IOException e) {
            System.err.println("Error: " + e.getMessage());
        }

        finally {
            if(out != null) {
                out.close();
            }
        }
    }
}
